In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/c_elegans_egg_xa.csv', comment='#')

xa_high = df.loc[df['food']=='high', 'area (sq. um)'].values
xa_low = df.loc[df['food']=='low', 'area (sq. um)'].values

In [5]:
def xa_to_diameter(xa):
    return np.sqrt(4 * xa/ np.pi)

In [10]:
Dia_high = xa_to_diameter(xa_high)
Dia_low = xa_to_diameter(xa_low)

In [11]:
xa_high

array([1683, 2061, 1792, 1852, 2091, 1781, 1912, 1802, 1751, 1731, 1892,
       1951, 1809, 1683, 1787, 1840, 1821, 1910, 1930, 1800, 1833, 1683,
       1671, 1680, 1692, 1800, 1821, 1882, 1642, 1749, 1712, 1661, 1701,
       2141, 1863, 1752, 1740, 1721, 1660, 1930, 2030, 1851, 2131, 1828])

In [12]:
Dia_high

array([46.29105911, 51.22642581, 47.76657057, 48.5596503 , 51.59790585,
       47.61973991, 49.33998388, 47.89966242, 47.21697198, 46.94654036,
       49.08125119, 49.84064959, 47.9926071 , 46.29105911, 47.69988539,
       48.40207395, 48.15152345, 49.3141717 , 49.57168871, 47.87307365,
       48.30991705, 46.29105911, 46.12573337, 46.24978308, 46.41466697,
       47.87307365, 48.15152345, 48.95137203, 45.72372833, 47.18999856,
       46.68817945, 45.98750791, 46.53794651, 52.2111661 , 48.70364742,
       47.23045291, 47.06842687, 46.81073869, 45.97366251, 49.57168871,
       50.8397116 , 48.54653847, 52.08909166, 48.24398292])

In [13]:
xa_low

array([1840, 2090, 2169, 1988, 2212, 2339, 1989, 2144, 2290, 1920, 2280,
       1809, 2158, 1800, 2133, 2060, 2160, 2001, 2030, 2088, 1951, 2460,
       2021, 2010, 2139, 2160, 2106, 2171, 2113, 2179, 1890, 2179, 2021,
       1969, 2150, 1900, 2267, 1711, 1901, 2114, 2112, 2361, 2130, 2061,
       2121, 1832, 2210, 2130, 2153, 2009, 2100, 2252, 2143, 2252, 2222,
       2121, 2409])

In [14]:
Dia_low

array([48.40207395, 51.58556628, 52.55146594, 50.31103472, 53.06982074,
       54.57203767, 50.32368681, 52.24773281, 53.99739399, 49.44309786,
       53.87936676, 47.9926071 , 52.41804019, 47.87307365, 52.11352942,
       51.21399674, 52.44232467, 50.47526453, 50.8397116 , 51.56087828,
       49.84064959, 55.96578669, 50.72688754, 50.58864976, 52.18677405,
       52.44232467, 51.78264653, 52.57568879, 51.86863366, 52.67246879,
       49.05530287, 52.67246879, 50.72688754, 50.07003758, 52.32078957,
       49.18490759, 53.72554372, 46.67454189, 49.19784929, 51.88090591,
       51.85635852, 54.8280819 , 52.07686848, 51.22642581, 51.96673046,
       48.29673743, 53.04582353, 52.07686848, 52.35727972, 50.57606396,
       51.70882946, 53.54750652, 52.23554675, 53.54750652, 53.18964437,
       51.96673046, 55.38261517])

Exercise 4.3

In [15]:
A = np.array(
    [
        [6.7, 1.3, 0.6, 0.7],
        [0.1, 5.5, 0.4, 2.4],
        [1.1, 0.8, 4.5, 1.7],
        [0.0, 1.5, 3.4, 7.5],
    ]
)

b = np.array([1.1, 2.3, 3.3, 3.9])

In [16]:
A[0]

array([6.7, 1.3, 0.6, 0.7])

In [20]:
A[:,[0,2]]

array([[6.7, 0.6],
       [0.1, 0.4],
       [1.1, 4.5],
       [0. , 3.4]])

In [23]:
A[A>2]

array([6.7, 5.5, 2.4, 4.5, 3.4, 7.5])

In [24]:
np.diag(A)

array([6.7, 5.5, 4.5, 7.5])

In [27]:
x = np.linalg.solve(A,b)
x

array([0.03401232, 0.29137092, 0.60186517, 0.18888027])

In [28]:
np.dot(A,x)

array([1.1, 2.3, 3.3, 3.9])

In [29]:
np.transpose(A)

array([[6.7, 0.1, 1.1, 0. ],
       [1.3, 5.5, 0.8, 1.5],
       [0.6, 0.4, 4.5, 3.4],
       [0.7, 2.4, 1.7, 7.5]])

In [30]:
np.linalg.inv(A)

array([[ 0.15267508, -0.03365026, -0.01778   ,  0.00054854],
       [-0.00906001,  0.19788853,  0.03719385, -0.07090934],
       [-0.04391535, -0.0144834 ,  0.26880108, -0.05219479],
       [ 0.02172029, -0.0330119 , -0.12929526,  0.17117684]])

In [32]:
B = np.ravel(A)
B

array([6.7, 1.3, 0.6, 0.7, 0.1, 5.5, 0.4, 2.4, 1.1, 0.8, 4.5, 1.7, 0. ,
       1.5, 3.4, 7.5])

In [33]:
np.reshape(A, (4,4))

array([[6.7, 1.3, 0.6, 0.7],
       [0.1, 5.5, 0.4, 2.4],
       [1.1, 0.8, 4.5, 1.7],
       [0. , 1.5, 3.4, 7.5]])

In [10]:
import numpy as np
import pandas as pd

import iqplot

import colorcet

import bokeh.io
import bokeh.plotting
import bokeh.models
import bokeh.themes

bokeh.io.output_notebook()

Loading BokehJS ...

In [11]:
%load_ext blackcellmagic

The blackcellmagic extension is already loaded. To reload it, use:
  %reload_ext blackcellmagic


In [12]:
data = np.random.default_rng().normal(0, 1, size=100)


def ecdf_vals(data):
    np_sort = np.sort(data)
    np_y = np.arange(1, len(np_sort) + 1) / len(np_sort)
    return np_sort, np_y

In [13]:
print(ecdf_vals(data))

(array([-2.02973405, -1.72794934, -1.68203837, -1.59671301, -1.50783032,
       -1.48664958, -1.4491273 , -1.40135079, -1.36108474, -1.22244093,
       -1.17260604, -1.10321659, -1.09288144, -1.05826085, -1.01203135,
       -0.95148723, -0.94458911, -0.89253765, -0.85177178, -0.80453601,
       -0.76799937, -0.65258824, -0.64032368, -0.63285185, -0.4447493 ,
       -0.37377524, -0.35083771, -0.31697981, -0.31343577, -0.26582869,
       -0.22995092, -0.21957627, -0.2061552 , -0.18810724, -0.18487514,
       -0.15586464, -0.15514626, -0.12703175, -0.12034173, -0.09776649,
       -0.09292508, -0.07019702, -0.05942481, -0.05600789,  0.04445582,
        0.07077317,  0.08161545,  0.09551309,  0.14967637,  0.15695966,
        0.19101974,  0.22608107,  0.26445187,  0.27225223,  0.28460318,
        0.29697278,  0.32649352,  0.34882203,  0.36375856,  0.3679852 ,
        0.37905888,  0.42804905,  0.430958  ,  0.51742186,  0.53154368,
        0.55813791,  0.56137825,  0.59109442,  0.60887944,  0.6

In [14]:
x,y = ecdf_vals(data)

p = bokeh.plotting.figure(
    frame_height=200,
    frame_width=300,
    x_axis_label='x',
    y_axis_label='ECDF',
)

p.circle(x, y)

bokeh.io.show(p)

In [15]:
df1 = pd.read_csv('data/wt_lac.csv', comment='#')
df1['Genotype']='WT'
df2 = pd.read_csv('data/q18a_lac.csv', comment='#')
df2['Genotype']='Q18A'
df3 = pd.read_csv('data/q18m_lac.csv', comment='#')
df3['Genotype']='Q18M'

In [16]:
df_tot = pd.concat([df1,df2,df3], ignore_index=True)
x = df_tot.loc[df_tot['Genotype']=='WT','[IPTG] (mM)']
print(df_tot)

    [IPTG] (mM)  fold change Genotype
0      0.000010     0.040697       WT
1      0.000974     0.072788       WT
2      0.002044     0.105284       WT
3      0.004049     0.199477       WT
4      0.007584     0.343024       WT
..          ...          ...      ...
60     1.551112     0.239704     Q18M
61     3.182057     0.237620     Q18M
62     6.202874     0.233039     Q18M
63    13.391757     0.233452     Q18M
64    26.086335     0.236279     Q18M

[65 rows x 3 columns]


In [17]:
cat_colors = colorcet.b_glasbey_category10
x = '[IPTG] (mM)'
y = 'fold change'

source_WT = bokeh.models.ColumnDataSource(df_tot.loc[df_tot['Genotype']=='WT', :])
source_Q18A = bokeh.models.ColumnDataSource(df_tot.loc[df_tot['Genotype']=='Q18A', :])
source_Q18M = bokeh.models.ColumnDataSource(df_tot.loc[df_tot['Genotype']=='Q18M', :])

p = bokeh.plotting.figure(
    frame_width = 300,
    frame_height = 300,
    x_axis_label = '[IPTG] (mM)',
    y_axis_label = 'fold change',
    x_range = [0.00001,100],
    y_range = [0,1.2],
    x_axis_type='log',
)

#source = bokeh.models.ColumnDataSource(df) #notneeded

WT_glyph = p.circle(
    source=source_WT,#or put df here directly
    x=x,
    y=y,
    color = cat_colors[0],
)

Q18A_glyph = p.circle(
    source=source_Q18A,#or put df here directly
    x=x,
    y=y,
    color = cat_colors[1],
)

Q18M_glyph = p.circle(
    source=source_Q18M,#or put df here directly
    x=x,
    y=y,
    color = cat_colors[2],
)

# Construct legend items
legend_items = [('WT', [WT_glyph]), ('Q18A', [Q18A_glyph]), ('Q18M', [Q18M_glyph])]

# Instantiate legend
legend = bokeh.models.Legend(items=legend_items, click_policy='hide')

# Add the legend to the right of the plot
p.add_layout(legend, 'right')

bokeh.io.show(p)

In [18]:
def fold_change(c, RK, KdA=0.017, KdI=0.002, Kswitch=5.8):
    return (1+RK*np.square(1+c/KdA)/(np.square(1+c/KdA)+Kswitch*np.square(1+c/KdI))) ** (-1)

In [19]:
d = np.logspace(-4,2,num = 1000)
#print(d)
#WT_fc = fold_change(df_tot.loc[df_tot['Genotype']=='WT', '[IPTG] (mM)'],141.5)
#Q18A_fc = fold_change(df_tot.loc[df_tot['Genotype']=='Q18A', '[IPTG] (mM)'],16.56)
#Q18M_fc = fold_change(df_tot.loc[df_tot['Genotype']=='Q18M', '[IPTG] (mM)'],1332)

WT_fc = fold_change(d,141.5)
Q18A_fc = fold_change(d,16.56)
Q18M_fc = fold_change(d,1332)

In [20]:
cat_colors = colorcet.b_glasbey_category10
x = '[IPTG] (mM)'
y = 'fold change'

source_WT = bokeh.models.ColumnDataSource(df_tot.loc[df_tot['Genotype']=='WT', :])
source_Q18A = bokeh.models.ColumnDataSource(df_tot.loc[df_tot['Genotype']=='Q18A', :])
source_Q18M = bokeh.models.ColumnDataSource(df_tot.loc[df_tot['Genotype']=='Q18M', :])

p = bokeh.plotting.figure(
    frame_width = 300,
    frame_height = 300,
    x_axis_label = '[IPTG] (mM)',
    y_axis_label = 'fold change',
    x_range = [0.00001,100],
    y_range = [0,1.2],
    x_axis_type='log',
)

#source = bokeh.models.ColumnDataSource(df) #notneeded

WT_glyph = p.circle(
    source=source_WT,#or put df here directly
    x=x,
    y=y,
    color = cat_colors[0],
)

Q18A_glyph = p.circle(
    source=source_Q18A,#or put df here directly
    x=x,
    y=y,
    color = cat_colors[1],
)

Q18M_glyph = p.circle(
    source=source_Q18M,#or put df here directly
    x=x,
    y=y,
    color = cat_colors[2],
)

p.line(
    #source=source_WT,#or put df here directly
    #x=df_tot.loc[df_tot['Genotype']=='WT', '[IPTG] (mM)'],
    x=d,
    y=WT_fc,
    color = cat_colors[0],
)

p.line(
    #source=source_Q18A,#or put df here directly
    #x=df_tot.loc[df_tot['Genotype']=='Q18A', '[IPTG] (mM)'],
    x=d,
    y=Q18A_fc,
    color = cat_colors[1],
)
p.line(
    #source=source_Q18M,#or put df here directly
    #x=df_tot.loc[df_tot['Genotype']=='Q18M', '[IPTG] (mM)'],
    x=d,
    y=Q18M_fc,
    color = cat_colors[2],
)
# Construct legend items
legend_items = [('WT', [WT_glyph]), ('Q18A', [Q18A_glyph]), ('Q18M', [Q18M_glyph])]

# Instantiate legend
legend = bokeh.models.Legend(items=legend_items, click_policy='hide')

# Add the legend to the right of the plot
p.add_layout(legend, 'right')

bokeh.io.show(p)

In [21]:
def bohr_parameter(c, RK, KdA=0.017, KdI=0.002, Kswitch=5.8):
    return -np.log(RK) - np.log(np.square(1+c/KdA)/(np.square(1+c/KdA)+Kswitch*np.square(1+c/KdI)))

In [22]:
def fold_change_bohr(bohr_parameter):
    return (1 + np.exp(-1*bohr_parameter))**(-1)

In [23]:
bp = np.arange(-6,6, step = 0.01)

In [24]:
FC_thr_bp = fold_change_bohr(bp)

In [25]:
p = bokeh.plotting.figure(
    frame_width = 300,
    frame_height = 300,
    x_axis_label = 'bohr parameter',
    y_axis_label = 'fold change',
    x_range = [-7,7],
    y_range = [0,1.2],
    #x_axis_type='log',
)

p.line(
    #source=source_Q18M,#or put df here directly
    #x=df_tot.loc[df_tot['Genotype']=='Q18M', '[IPTG] (mM)'],
    x=bp,
    y=FC_thr_bp,
    color = 'grey',
)

bokeh.io.show(p)

In [26]:
WT_bohr = bohr_parameter(df_tot.loc[df_tot['Genotype']=='WT', '[IPTG] (mM)'],141.5)
Q18A_bohr = bohr_parameter(df_tot.loc[df_tot['Genotype']=='Q18A', '[IPTG] (mM)'],16.56)
Q18M_bohr = bohr_parameter(df_tot.loc[df_tot['Genotype']=='Q18M', '[IPTG] (mM)'],1332)

p = bokeh.plotting.figure(
    frame_width = 300,
    frame_height = 300,
    x_axis_label = 'bohr parameter',
    y_axis_label = 'fold change',
    x_range = [-7,7],
    y_range = [0,1.2],
    #x_axis_type='log',
)

Bohr = p.line(
    #source=source_Q18M,#or put df here directly
    #x=df_tot.loc[df_tot['Genotype']=='Q18M', '[IPTG] (mM)'],
    x=bp,
    y=FC_thr_bp,
    color = 'grey',
)

WT_glyph = p.circle(
    #source=source_WT,#or put df here directly
    x=WT_bohr,
    y=fold_change_bohr(WT_bohr),
    color = cat_colors[0],
)

Q18A_glyph = p.circle(
    #source=source_Q18A,#or put df here directly
    x=Q18A_bohr,
    y=fold_change_bohr(Q18A_bohr),
    color = cat_colors[1],
)

Q18M_glyph = p.circle(
    #source=source_Q18M,#or put df here directly
    x=Q18M_bohr,
    y=fold_change_bohr(Q18M_bohr),
    color = cat_colors[2],
)

# Construct legend items
legend_items = [('WT', [WT_glyph]), ('Q18A', [Q18A_glyph]), ('Q18M', [Q18M_glyph]), ('Theoretical Fold Change', [Bohr])]

# Instantiate legend
legend = bokeh.models.Legend(items=legend_items, click_policy='hide')

# Add the legend to the right of the plot
p.add_layout(legend, 'right')

bokeh.io.show(p)